### ISSUE TITLE
gitlab install

### ISSUE THREAD

**Issue by asu126** [asu126/learn#1]
install:
http://docs.gitlab.com/ce/install/installation.html
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md
https://about.gitlab.com/downloads/#ubuntu1404

**Comment by suguojun** [comment]
git@su-Lenovo-IdeaPad-Y480:~/gitlab-development-kit$ make
git clone https://gitlab.com/gitlab-org/gitlab-ce.git gitlab
正克隆到 'gitlab'...
remote: Counting objects: 356572, done.
remote: Compressing objects: 100% (86522/86522), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed
Makefile:21: recipe for target 'gitlab/.git' failed
make: *** [gitlab/.git] Error 128
git@su-Lenovo-IdeaPad-Y480:~/gitlab-development-kit$ make
git clone https://gitlab.com/gitlab-org/gitlab-ce.git gitlab
正克隆到 'gitlab'...
fatal: unable to access 'https://gitlab.com/gitlab-org/gitlab-ce.git/': GnuTLS recv error (-54): Error in the pull function.
Makefile:21: recipe for target 'gitlab/.git' failed
make: *** [gitlab/.git] Error 128

**Comment by suguojun** [comment]
1、ruby gem 源问题：------ sudo gem install bundle
参考 http://code.huawei.com/codeclub/gitlab/blob/develop/Gemfile
解决：  gem source
		sudo gem source -r https://rubygems.org/
		sudo gem source -a http://rnd-mirrors-langfang.huawei.com/rubygems/

2、bundle exec rake db:create  psql 数据库没有创建
3、/home/git/gitlab-development-ki/Procfile



git 配置文件：/gitlab/config/gitlab.yml

 vim Procfile  删除 redis

**Comment by suguojun** [comment]
cat HELP
# GitLab Development Kit cheat sheet

gdk run            # Start everything
gdk run db         # Start enough to run tests
gdk run app        # Start GitLab, needs 'gdk run db'

gdk install gitlab_repo=https://my-fork   # Install everything
gdk update                                # Pull application changes from Git
gdk reconfigure                           # Delete and regenerate all config files created by GDK

# Development admin account: root / 5iveL!fe
*********************************************

**Comment by suguojun** [comment]
sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=development

**Comment by suguojun** [comment]
http
repositories
git clone http://localhost:3000/repositories/asu/01.git

**Comment by suguojun** [comment]
command -v bundler > /dev/null || gem install bundler
GOPATH=/home/git/gitlab-development-kit/gitlab-workhorse go install gitlab.com/gitlab-org/gitlab-workhorse/...
command -v foreman > /dev/null || gem install foreman

*********************************************
************** Setup finished! **************
*********************************************
cat HELP
# GitLab Development Kit cheat sheet

gdk run            # Start everything
gdk run db         # Start enough to run tests
gdk run app        # Start GitLab, needs 'gdk run db'

gdk install gitlab_repo=https://my-fork   # Install everything
gdk update                                # Pull application changes from Git
gdk reconfigure                           # Delete and regenerate all config files created by GDK

# Development admin account: root / 5iveL!fe

**Comment by suguojun** [comment]
Documentcloud / Underscore ... repository is empty
Gitlab Org / Gitlab Ce ... repository is empty
Gitlab Org / Gitlab Ci ... repository is empty
Gitlab Org / Gitlab Shell ... repository is empty
Gitlab Org / Gitlab Test ... repository is empty
Twitter / Flight ... repository is empty
Twitter / Typeahead.Js ... repository is empty
H5bp / Html5 Boilerplate ... repository is empty

**Comment by suguojun** [comment]
bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=development

**Comment by suguojun** [comment]
sudo apt-get --purge autoremove postgresql*

**Comment by suguojun** [comment]
bin/rake db:migrate RAILS_ENV=development

**Comment by asu126** [comment]
update users set admin=true where id=1;

**Comment by asu126** [comment]
psql -h "/home/git/gitlab-development-kit/postgresql" gitlabhq_development

**Comment by asu126** [comment]
cd /home/su/gitlab-development-kit/gitlab
su@su-Lenovo-IdeaPad-Y480:~/gitlab-development-kit/gitlab$ bundle exec rake gitlab:check RAILS_ENV=development
D, [2017-02-12T11:49:59.103433 #967] DEBUG -- sentry: ** [Raven] cannot load such file -- haml_lint/rake_task excluded from capture due to environment or should_capture callback
rake aborted!
LoadError: cannot load such file -- haml_lint/rake_task

**Comment by asu126** [comment]
```
webpack output is served from //localhost:3808/assets/webpack/
D, [2017-02-12T11:56:42.120831 #1197] DEBUG -- sentry: ** [Raven] cannot load such file -- haml_lint/rake_task excluded from capture due to environment or should_capture callback
rake aborted!
LoadError: cannot load such file -- haml_lint/rake_task
```

**Comment by asu126** [comment]
npm WARN optional dep failed, continuing fsevents@1.1.1

**Comment by asu126** [comment]
cd /home/su/gitlab-development-kit/gitlab && npm install

**Comment by asu126** [comment]
npm config set registry "http://r.cnpmjs.org/"

**Comment by asu126** [comment]
https://www.cnblogs.com/laozhbook/p/npm_help.html

**Comment by asu126** [comment]
https://segmentfault.com/a/1190000002642514

**Comment by asu126** [comment]
http://riny.net/2014/cnpm/

**Comment by asu126** [comment]
/usr/local/bin/sidekiq -C /home/su/gitlab-development-kit/gitlab/config/sidekiq_queues.yml -e development -P /home/su/gitlab-development-kit/gitlab/tmp/pids/sidekiq.pid
